***************************1. IMPORT, REFINE & ANALYSE**************************

clear all
set more off

cd "C:\Users\point\OneDrive\Documents\Standard Files\University\Stage 3\EC541\Data\LFS" // replace with your directory

*************for help with any file simply type help "command name"*************

****************************A.Loading/Importing Data****************************
use "2020-Q3\UKDA-8720-stata\stata\stata13\lfsp_js20_eul_pwt18.dta"
gen year=2020
gen quarter=3
gen EMPTEN=2020-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_20_Q3.dta", replace


use "2020-Q2\UKDA-8671-stata\stata\stata13\lfsp_aj20_eul_pwt18.dta"
gen year=2020
gen quarter=2
gen EMPTEN=2020-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_20_Q2.dta", replace

use "2020-Q1\UKDA-8639-stata\stata\stata13\lfsp_jm20_eul_pwt18.dta"
gen year=2020
gen quarter=1
gen EMPTEN=2020-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_20_Q1.dta", replace

use "2019-Q4\UKDA-8614-stata\stata\stata13\lfsp_od19_eul.dta"
gen year=2019
gen quarter=4
gen EMPTEN=2019-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_19_Q4.dta", replace

use "2019-Q3\UKDA-8588-stata\stata\stata11\lfsp_js19_eul.dta"
gen year=2019
gen quarter=3
gen EMPTEN=2019-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_19_Q3.dta", replace

use "2019-Q2\UKDA-8563-stata\stata\stata13\lfsp_aj19_eul_pwt18.dta"
gen year=2019
gen quarter=2
gen EMPTEN=2019-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_19_Q2.dta", replace

use "2019-Q1\UKDA-8485-stata\stata\stata13\lfsp_jm19_eul_pwt18.dta"
gen year=2019
gen quarter=1
gen EMPTEN=2019-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_19_Q1.dta", replace

use "2018-Q4\UKDA-8447-stata\stata\stata11\lfsp_od18_end_user_pwt18.dta"
gen year=2018
gen quarter=4
gen EMPTEN=2018-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_18_Q4.dta", replace

use "2018-Q3\UKDA-8407-stata\stata\stata11\lfsp_js18_eul.dta"
gen year=2018
gen quarter=3
gen EMPTEN=2018-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_18_Q3.dta", replace

use "2018-Q2\UKDA-8381-stata\stata\stata11\lfsp_aj18_eul.dta"
gen year=2018
gen quarter=2
gen EMPTEN=2018-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_18_Q2.dta", replace

use "2018-Q1\UKDA-8343-stata\stata\stata11\lfsp_jm18_eul.dta"
gen year=2018
gen quarter=1
gen EMPTEN=2018-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_18_Q1.dta", replace

use "2017-Q4\UKDA-8326-stata\stata\stata11\lfsp_od17_eul.dta"
gen year=2017
gen quarter=4
gen EMPTEN=2017-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_17_Q4.dta", replace

use "2017-Q3\UKDA-8292-stata\stata\stata11\lfsp_js17_eul.dta"
gen year=2017
gen quarter=3
gen EMPTEN=2017-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_17_Q3.dta", replace

use "2017-Q2\UKDA-8235-stata\stata\stata11\lfsp_aj17_eul.dta"
gen year=2017
gen quarter=2
gen EMPTEN=2017-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_17_Q2.dta", replace

use "2017-Q1\UKDA-8195-stata\stata\stata11\lfsp_jm17_eul.dta"
gen year=2017
gen quarter=1
gen EMPTEN=2017-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_17_Q1.dta", replace

use "2016-Q4\UKDA-8145-stata\stata\stata11\lfsp_od16_eul.dta"
gen year=2016
gen quarter=4
gen EMPTEN=2016-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_16_Q4.dta", replace

use "2016-Q3\UKDA-8104-stata\stata\stata11\lfsp_js16_eul.dta"
gen year=2016
gen quarter=3
gen EMPTEN=2016-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_16_Q3.dta", replace

use "2016-Q2\UKDA-8039-stata11\stata11\lfsp_aj16_eul.dta"
drop year
gen year=2016 //year of study
gen quarter=2 //quarter of study
gen EMPTEN=2016-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_16_Q2.dta", replace

use "2016-Q1\UKDA-7985-stata11\stata11\lfsp_jm16_eul.dta"
gen year=2016
gen quarter=1
gen EMPTEN=2016-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_16_Q1.dta", replace

use "2015-Q4\UKDA-7902-stata11\stata11\lfsp_od15_end_user.dta"
gen year=2015
gen quarter=4
gen EMPTEN=2015-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_15_Q4.dta", replace

use "2015-Q3\UKDA-7842-stata\stata\stata11\lfsp_js15_eul.dta"
*NOTE THAT MANY VARS HAVE GOT DIFFERENT NAMES FOR THIS ONE.
gen year=2015
gen quarter=3
gen EMPTEN=2015-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_15_Q3.dta", replace

use  "2015-Q2\UKDA-7781-stata11\stata11\lfsp_aj15_eul.dta"
gen year=2015
gen quarter=2
gen EMPTEN=2015-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_15_Q2.dta", replace

use  "2015-Q1\UKDA-7725-stata11\stata11\lfsp_jm15_eul.dta"
gen year=2015
gen quarter=1
gen EMPTEN=2015-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 CLAIMS14 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_15_Q1.dta", replace

use  "2014-Q4\UKDA-7664-stata\stata\stata11\lfsp_od14_eul.dta"
gen year=2014
gen quarter=4
gen EMPTEN=2014-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M  MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENTYP5 QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_14_Q4.dta", replace

use  "2014-Q3\UKDA-7570-stata\stata\stata11\lfsp_js14_end_user.dta"
gen year=2014
gen quarter=3
gen EMPTEN=2014-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_14_Q3.dta", replace

use  "2014-Q2\UKDA-7557-stata\stata\stata11\lfsp_aj14_end_user.dta"
gen year=2014
gen quarter=2
gen EMPTEN=2014-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_14_Q2.dta", replace

use  "2014-Q1\UKDA-7501-stata\stata\stata11\lfsp_jm14_end_user.dta"
gen year=2014
gen quarter=1
gen EMPTEN=2014-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_14_Q1.dta", replace

use  "2013-Q4\UKDA-7468-stata\stata\stata11\lfsp_od13_end_user.dta"
gen year=2013
gen quarter=4
gen EMPTEN=2013-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_13_Q4.dta", replace

use  "2013-Q3\UKDA-7452-stata\stata\stata11\lfsp_js13_end_user.dta"
gen year=2013
gen quarter=3
gen EMPTEN=2013-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_13_Q3.dta", replace

use  "2013-Q2\UKDA-7376-stata\stata\stata11\lfsp_aj13_end_user.dta"
gen year=2013
gen quarter=2
gen EMPTEN=2013-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_13_Q2.dta", replace

use  "2013-Q1\UKDA-7277-stata\stata\stata11\lfsp_jm13_end_user.dta"
gen year=2013
gen quarter=1
gen EMPTEN=2013-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_13_Q1.dta", replace

use  "2012-Q4\UKDA-7220-stata\stata\stata11\lfsp_od12_end_user.dta"
gen year=2012
gen quarter=4
gen EMPTEN=2012-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_12_Q4.dta", replace

use  "2012-Q3\UKDA-7174-stata\stata\stata11\lfsp_js12_end_user.dta"
gen year=2012
gen quarter=3
gen EMPTEN=2012-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_12_Q3.dta", replace

use  "2012-Q2\UKDA-7108-stata\stata\stata11\lfsp_aj12_end_user.dta"
gen year=2012
gen quarter=2
gen EMPTEN=2012-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_12_Q2.dta", replace

use  "2012-Q1\UKDA-7037-stata\stata\stata11\lfsp_jm12_end_user.dta"
gen year=2012
gen quarter=1
gen EMPTEN=2012-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEGB STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_12_Q1.dta", replace

use  "2011-Q4\UKDA-6975-stata\stata\stata11\lfsp_od11_end_user_pwt18.dta"
gen year=2011
gen quarter=4
gen EMPTEN=2011-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_11_Q4.dta", replace

use  "2011-Q3\UKDA-6906-stata\stata\stata11\lfsp_js11_end_user_pwt18.dta"
gen year=2011
gen quarter=3
gen EMPTEN=2011-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_11_Q3.dta", replace

use  "2011-Q2\UKDA-6851-stata11\stata11\lfsp_aj11_end_user.dta"
gen year=2011
gen quarter=2
gen EMPTEN=2011-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHEWEUL ETHGBEUL ETHUKEUL RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_11_Q2.dta", replace

use  "2011-Q1\UKDA-6782-stata11\stata11\lfsp_jm11_end_user.dta"
gen year=2011
gen quarter=1
gen EMPTEN=2011-CONMPY
keep SC10MMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM QUAL_1 HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHCEN15 ETHUK14 ETHUK8 RELIG* LEVQUL* UNEMBN1 BENFTS QUAL_1 SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_11_Q1.dta", replace

use  "2010-Q4\UKDA-6715-stata11\stata11\lfsp_od10_end_user.dta"
gen year=2010
gen quarter=4
gen EMPTEN=2010-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_10_Q4.dta", replace

use  "2010-Q3\UKDA-6632-stata11\stata11\lfsp_js10_end_user.dta"
gen year=2010
gen quarter=3
gen EMPTEN=2010-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_10_Q3.dta", replace

use  "2010-Q2\UKDA-6548-stata11\stata11\lfsp_aj10_end_user.dta"
gen year=2010
gen quarter=2
gen EMPTEN=2010-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_10_Q2.dta", replace

use  "2010-Q1\UKDA-6457-stata11\stata11\lfsp_jm10_end_user.dta"
gen year=2010
gen quarter=1
gen EMPTEN=2010-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_10_Q1.dta", replace

use  "2009-Q4\UKDA-6404-stata11\stata11\lfsp_od09_end_user.dta"
gen year=2009
gen quarter=4
gen EMPTEN=2009-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_09_Q4.dta", replace

use  "2009-Q3\UKDA-6334-stata11\stata11\lfsp_js09_end_user.dta"
gen year=2009
gen quarter=3
gen EMPTEN=2009-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_09_Q3.dta", replace

use  "2009-Q2\UKDA-6276-stata11\stata11\lfsp_aj09_end_user.dta"
gen year=2009
gen quarter=2
gen EMPTEN=2009-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_09_Q2.dta", replace

use  "2009-Q1\UKDA-6199-stata11\stata11\lfsp_jm09_end_user.dta"
gen year=2009
gen quarter=1
gen EMPTEN=2009-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV IN0792DM IN0792EM DEGREE* HSERIALP PIWT* year quarter INDD07M MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_09_Q1.dta", replace

use  "2008-Q4\UKDA-6119-stata11\stata11\lfsp_od08_end_user.dta"
gen year=2008
gen quarter=4
gen EMPTEN=2008-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_08_Q4.dta", replace

use  "2008-Q3\UKDA-6074-stata11\stata11\lfsp_js08_end_user.dta"
gen year=2008
gen quarter=3
gen EMPTEN=2008-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_08_Q3.dta", replace

use  "2008-Q2\UKDA-6013-stata11\stata11\lfsp_aj08_end_user.dta"
gen year=2008
gen quarter=2
gen EMPTEN=2008-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_08_Q2.dta", replace

use  "2008-Q1\UKDA-5851-stata11\stata11\lfsp_jm08_end_user.dta"
gen year=2008
gen quarter=1
gen EMPTEN=2008-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_08_Q1.dta", replace

use  "2007-Q4\UKDA-5796-stata11\stata11\lfsp_od07_end_user.dta"
gen year=2007
gen quarter=4
gen EMPTEN=2007-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_07_Q4.dta", replace

use  "2007-Q3\UKDA-5763-stata11\stata11\lfsp_js07_end_user.dta"
gen year=2007
gen quarter=3
gen EMPTEN=2007-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_07_Q3.dta", replace

use  "2007-Q2\UKDA-5715-stata11\stata11\lfsp_aj07_end_user.dta"
gen year=2007
gen quarter=2
gen EMPTEN=2007-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_07_Q2.dta", replace

use  "2007-Q1\UKDA-5657-stata11\stata11\lfsp_jm07_end_user.dta"
gen year=2007
gen quarter=1
gen EMPTEN=2007-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_07_Q1.dta", replace

use  "2006-Q4\UKDA-5609-stata11\stata11\lfsp_od06_end_user.dta"
gen year=2006
gen quarter=4
gen EMPTEN=2006-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_06_Q4.dta", replace

use  "2006-Q3\UKDA-5547-stata11\stata11\lfsp_js06_end_user.dta"
gen year=2006
gen quarter=3
gen EMPTEN=2006-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_06_Q3.dta", replace

use  "2006-Q2\UKDA-5466-stata11\stata11\lfsp_aj06_end_user.dta"
gen year=2006
gen quarter=2
gen EMPTEN=2006-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_06_Q2.dta", replace

use  "2006-Q1\UKDA-5369-stata11\stata11\lfsp_jm06_end_user.dta"
gen year=2006
gen quarter=1
gen EMPTEN=2006-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_06_Q1.dta", replace

use  "2005-Q4\UKDA-5429-stata11\stata11\lfsp_od05_end_user.dta"
gen year=2005
gen quarter=4
gen EMPTEN=2005-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_05_Q4.dta", replace

use  "2005-Q3\UKDA-5428-stata11\stata11\lfsp_js05_end_user.dta"
gen year=2005
gen quarter=3
gen EMPTEN=2005-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 UNDEMP
sa "Output\LFS_05_Q3.dta", replace

use  "2005-Q2\UKDA-5427-stata11\stata11\lfsp_aj05_end_user.dta"
gen year=2005
gen quarter=2
gen EMPTEN=2005-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECAC05 PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL5 GCSEFUL1 GCSEFUL2 UNDEMP
sa "Output\LFS_05_Q2.dta", replace

use  "2005-Q1\UKDA-5426-stata11\stata11\lfsp_jm05_end_user.dta"
gen year=2005
gen quarter=1
gen EMPTEN=2005-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL GCSEFUL1 GCSEFUL2 UNDEMP
sa "Output\LFS_05_Q1.dta", replace

use  "2004-Q4\UKDA-5425-stata11\stata11\lfsp_od04_end_user.dta"
gen year=2004
gen quarter=4
gen EMPTEN=2004-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* GCSEFUL1 GCSEFUL2 UNDEMP
sa "Output\LFS_04_Q4.dta", replace

use  "2004-Q3\UKDA-5843-stata11\stata11\lfsp_js04_end_user.dta"
gen year=2004
gen quarter=3
gen EMPTEN=2004-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* GCSEFUL1 GCSEFUL2 UNDEMP
sa "Output\LFS_04_Q3.dta", replace

use  "2004-Q2\UKDA-5424-stata11\stata11\lfsp_aj04_end_user.dta"
gen year=2004
gen quarter=2
gen EMPTEN=2004-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* GCSEFUL1 GCSEFUL2 UNDEMP
sa "Output\LFS_04_Q2.dta", replace

*Missing key information - such as GCSEs and highest qualification
use  "2004-Q1\UKDA-5842-stata11\stata11\lfsp_jm04_end_user.dta"
gen year=2004
gen quarter=1
gen EMPTEN=2004-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV QUALS01 QUALS02 QUALS03 QUALS04 HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL UNDEMP
// Missing the following vars: NUMOL* GCSEFUL1 GCSEFUL2*/
sa "Output\LFS_04_Q1.dta", replace


use  "2003-Q4\UKDA-5423-stata11\stata11\lfsp_od03_end_user.dta"
gen year=2003
gen quarter=4
gen EMPTEN=2003-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_03_Q4.dta", replace

use  "2003-Q3\UKDA-5845-stata11\stata11\lfsp_js03_end_user.dta"
gen year=2003
gen quarter=3
gen EMPTEN=2003-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_03_Q3.dta", replace

use  "2003-Q2\UKDA-5422-stata11\stata11\lfsp_aj03_end_user.dta"
gen year=2003
gen quarter=2
gen EMPTEN=2003-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_03_Q2.dta", replace

use  "2003-Q1\UKDA-5844-stata11\stata11\lfsp_jm03_end_user.dta"
gen year=2003
gen quarter=1
gen EMPTEN=2003-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_03_Q1.dta", replace

use  "2002-Q4\UKDA-5421-stata11\stata11\lfsp_od02_end_user.dta"
gen year=2002
gen quarter=4
gen EMPTEN=2002-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF2 FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_02_Q4.dta", replace

use  "2002-Q3\UKDA-5847-stata11\stata11\lfsp_js02_end_user.dta"
gen year=2002
gen quarter=3
gen EMPTEN=2002-CONMPY
keep SC2KMMJ HSERIALP CASENOP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_02_Q3.dta", replace

use  "2002-Q2\UKDA-5420-stata11\stata11\lfsp_aj02_end_user.dta"
gen year=2002
gen quarter=2
gen EMPTEN=2002-CONMPY
keep SC2KMMJ HSERIALP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR02 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 RELIG* LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_02_Q2.dta", replace

use  "2002-Q1\UKDA-5846-stata11\stata11\lfsp_jm02_end_user.dta"
gen year=2002
gen quarter=1
gen EMPTEN=2002-CONMPY
keep SC2KMMJ HSERIALP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR01 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 IREND2 LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_02_Q1.dta", replace

use  "2001-Q4\UKDA-5419-stata11\stata11\lfsp_od01_end_user.dta"
gen year=2001
gen quarter=4
gen EMPTEN=2001-CONMPY
keep SC2KMMJ HSERIALP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR01 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 IREND2 LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_01_Q4.dta", replace

use  "2001-Q3\UKDA-5855-stata11\stata11\lfsp_js01_end_user.dta"
gen year=2001
gen quarter=3
gen EMPTEN=2001-CONMPY
keep SC2KMMJ HSERIALP THISWV DEGREE* HSERIALP PIWT* year quarter MPNR01 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT EDAGE ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 IREND2 LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_01_Q3.dta", replace

use  "2001-Q2\UKDA-5418-stata8\stata8\qlfsaj01.dta"
gen year=2001
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename eth01 ETH01
rename irend2 IREND2 
rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename sc2kmmj SC2KMMJ
rename govtof GOVTOF
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR 
rename publicr PUBLICR
gen EMPTEN=2001-CONMPY
keep SC2KMMJ THISWV hiquald PIWT* year quarter oympr01 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETH01 IREND2 LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_01_Q2.dta", replace //FIRST YEAR OF NO HSERIALP DATA

/* - MISSING KEY ETHNICITY and PIWT INFO - if PIWT is not necessary then we could possibly use the 'cryox' variable to get the ethnicity data.
use  "2001-Q1\UKDA-5854-stata8\stata8\qlfsjm01.dta"
gen year=2001
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
//rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename govtof GOVTOF
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR 
gen EMPTEN=2001-CONMPY
keep SC2KMMJ HSERIALP THISWV DEGREE* year quarter MPNR01 PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ETHCEN* ETHMX IREND2 LEVQUAL* UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_01_Q1.dta", replace
*/

use  "2000-Q4\UKDA-5859-stata8\stata8\qlfsod00.dta"
gen year=2000
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename govtof GOVTOF
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR 
rename publicr PUBLICR
gen EMPTEN=2000-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_00_Q4.dta", replace

use  "2000-Q3\UKDA-5858-stata8\stata8\qlfsjs00.dta"
gen year=2000
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename govtof GOVTOF
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR 
rename publicr PUBLICR
gen EMPTEN=2000-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_00_Q3.dta", replace

use  "2000-Q2\UKDA-5857-stata8\stata8\qlfsaj00.dta"
gen year=2000
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename govtof GOVTOF
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR 
rename publicr PUBLICR
gen EMPTEN=2000-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK GOVTOF FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_00_Q2.dta", replace

use  "2000-Q1\UKDA-5856-stata8\stata8\qlfsjm00.dta"
gen year=2000
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
//rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=2000-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR bushr DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_00_Q1.dta", replace

use  "1999-Q4\UKDA-5417-stata8\stata8\qlfsod99.dta"
gen year=1999
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
//rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1999-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR bushr DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_99_Q4.dta", replace

use  "1999-Q3\UKDA-5864-stata8\stata8\qlfsjs99.dta"
gen year=1999
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
//rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1999-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR bushr DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_99_Q3.dta", replace

use  "1999-Q2\UKDA-5416-stata8\stata8\qlfsaj99.dta"
gen year=1999
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
//rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1999-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR bushr DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_99_Q2.dta", replace

use  "1999-Q1\UKDA-5863-stata8\stata8\qlfsjm99.dta"
gen year=1999
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
//rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1999-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR bushr DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_99_Q1.dta", replace

use  "1998-Q4\UKDA-5868-stata8\stata8\qlfsod98.dta"
gen year=1998
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1998-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_98_Q4.dta", replace

use  "1998-Q3\UKDA-5867-stata8\stata8\qlfsjs98.dta"
gen year=1998
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1998-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_98_Q3.dta", replace

use  "1998-Q2\UKDA-5866-stata8\stata8\qlfsaj98.dta"
gen year=1998
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
rename unembn1 UNEMBN1 
rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename discurr DISCURR
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1998-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA DISCURR* FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev UNEMBN1 BENFTS SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_98_Q2.dta", replace

use  "1998-Q1\UKDA-5865-stata8\stata8\qlfsjm98.dta"
gen year=1998
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename healyl HEALYL
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=1998-CONMPY //not sure if this sound be 98 or 1998 - same for Q2
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA HEALYL FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_98_Q1.dta", replace

use  "1997-Q4\UKDA-5415-stata8\stata8\qlfsod97.dta"
gen year=1997
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=97-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_97_Q4.dta", replace

use  "1997-Q3\UKDA-5870-stata8\stata8\qlfsjs97.dta"
gen year=1997
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
rename sincom SINCOM 
rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=97-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp SINCOM SNGDEG STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_97_Q3.dta", replace

use  "1997-Q2\UKDA-5414-stata8\stata8\qlfsaj97.dta"
gen year=1997
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=97-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_97_Q2.dta", replace

use  "1997-Q1\UKDA-5869-stata8\stata8\qlfsjm97.dta"
gen year=1997
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=97-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR subjct1 subjct1 MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_97_Q1.dta", replace

use  "1996-Q4\UKDA-5874-stata8\stata8\qlfsod96.dta"
gen year=1996
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=96-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR subjct1 MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev jsatyp STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_96_Q4.dta", replace

use  "1996-Q3\UKDA-5873-stata8\stata8\qlfsjs96.dta"
gen year=1996
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=96-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR subjct1 MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_96_Q3.dta", replace

use  "1996-Q2\UKDA-5872-stata8\stata8\qlfsaj96.dta"
gen year=1996
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=96-CONMPY
keep socmajm PIWT* degree* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR subjct1 MARDY* CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL* UNDEMP
sa "Output\LFS_96_Q2.dta", replace

use  "1996-Q1\UKDA-5871-stata8\stata8\qlfsjm96.dta"
gen year=1996
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=96-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA LNGLIM FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M INDSECT edage ILODEFR subjct1 marstt CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_96_Q1.dta", replace

use  "1995-Q4\UKDA-5878-stata8\stata8\qlfsod95.dta"
gen year=1995
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
//rename lnglim LNGLIM
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=95-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M edage ILODEFR subjct1 marstt CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_95_Q4.dta", replace

use  "1995-Q3\UKDA-5877-stata8\stata8\qlfsjs95.dta"
gen year=1995
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=95-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M edage ILODEFR subjct1 marstt CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_95_Q3.dta", replace

use  "1995-Q2\UKDA-5876-stata8\stata8\qlfsaj95.dta"
gen year=1995
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=95-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M edage ILODEFR subjct1 marstt CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_95_Q2.dta", replace

use  "1995-Q1\UKDA-5875-stata8\stata8\qlfsjm95.dta"
gen year=1995 //should this be 95??
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=95-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M edage ILODEFR subjct1 marstt CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic IREND2 nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_95_Q1.dta", replace

use  "1994-Q4\UKDA-5882-stata8\stata8\qlfsod94.dta"
gen year=1994
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=94-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor AGE SEX INDD92M edage ILODEFR subjct1 marcon CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_94_Q4.dta", replace

use  "1994-Q3\UKDA-5881-stata8\stata8\qlfsjs94.dta"
gen year=1994
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=94-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor AGE SEX INDD92M edage ILODEFR subjct1 marcon CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_94_Q3.dta", replace

use  "1994-Q2\UKDA-5880-stata8\stata8\qlfsaj94.dta"
gen year=1994
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=94-CONMPY
keep socmajm PIWT* THISWV year quarter mpnor PUBLICR INECACR PAIDHRA FTPTWK govtor AGE SEX INDD92M edage ILODEFR subjct1 marcon CAMEYR EMPTEN EMPLEN ethcen ethnica ethnic nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_94_Q2.dta", replace

use  "1994-Q1\UKDA-5879-stata8\stata8\qlfsjm94.dta"
gen year=1994
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
rename numol* NUMOL* 
//rename undemp UNDEMP
rename indd92m INDD92M
//rename indsect INDSECT
rename fdpch2 FDPCH2
rename fdpch4 FDPCH4
rename fdpch9 FDPCH9
rename fdpch15 FDPCH15
rename fdpch16 FDPCH16
rename fdpch19 FDPCH19
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=94-CONMPY //as skips the 19 part of any year e.g. 1964 is 64
keep socmajm PIWT* THISWV year quarter PUBLICR INECACR PAIDHRA FTPTWK govtor FDPCH2 FDPCH4 FDPCH9 FDPCH15 FDPCH16 FDPCH19 AGE SEX INDD92M edage ILODEFR subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic nvqlev STUCUR GRSSWK NUMAL NUMOL*
sa "Output\LFS_94_Q1.dta", replace

use  "1993-Q4\UKDA-5886-stata\stata\stata13\qlfsod93_eul.dta"
gen year=1993
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename ftptwk FTPTWK
rename paidhra PAIDHRA
rename inecacr INECACR
rename publicr PUBLICR
gen EMPTEN=93-CONMPY //as skips the 19 part of any year e.g. 1964 is 64
keep socmajm PIWT* THISWV year quarter PUBLICR INECACR PAIDHRA FTPTWK govtor AGE SEX edage ILODEFR subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic nvqlev STUCUR GRSSWK NUMAL
sa "Output\LFS_93_Q4.dta", replace

use  "1993-Q3\UKDA-5885-stata8\stata8\qlfsjs93.dta"
gen year=1993
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename ftptwk FTPTWK
//rename paidhra PAIDHRA
rename inecacr INECACR
//rename publicr PUBLICR
gen EMPTEN=93-CONMPY //as skips the 19 part of any year e.g. 1964 is 64
keep socmajm PIWT* THISWV year quarter FTPTWK govtor AGE SEX edage subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic nvqlev cured GRSSWK NUMAL INECACR
sa "Output\LFS_93_Q3.dta", replace

use  "1993-Q2\UKDA-5884-stata8\stata8\qlfsaj93.dta"
gen year=1993
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename ftptwk FTPTWK
//rename paidhra PAIDHRA
rename inecacr INECACR
//rename publicr PUBLICR
gen EMPTEN=93-CONMPY //as skips the 19 part of any year e.g. 1964 is 64
keep socmajm PIWT* THISWV year quarter FTPTWK govtor AGE SEX edage subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic nvqlev cured GRSSWK NUMAL INECACR
sa "Output\LFS_93_Q2.dta", replace

use  "1993-Q1\UKDA-5883-stata8\stata8\qlfsjm93.dta"
gen year=1993
gen quarter=1
rename conmpy CONMPY
rename thiswv THISWV
rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
//rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename ftptwk FTPTWK
//rename paidhra PAIDHRA
rename inecacr INECACR
//rename publicr PUBLICR
gen EMPTEN=93-CONMPY //as skips the 19 part of any year e.g. 1964 is 64
keep socmajm PIWT* THISWV year quarter FTPTWK govtor AGE SEX edage subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic cured GRSSWK qual0 qual1 qual2 INECACR
sa "Output\LFS_93_Q1.dta", replace

/* - MISSING KEY pay and PIWT INFO
use  "1992-Q4\UKDA-5889-stata8\stata8\qlfsod92.dta"
gen year=1992
gen quarter=4
rename conmpy CONMPY
rename thiswv THISWV
//rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
//rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename healyl HEALYL
rename paidhra PAIDHRA
gen EMPTEN=1992-CONMPY
keep socmajm THISWV qual0 qual1 qual2 year quarter mpnor PUBLICR INECACR PAIDHRA HEALYL FTPTWK govtor AGE SEX subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic cured GRSSWK qual0 qual1 qual2
sa "Output\LFS_92_Q4.dta", replace

use  "1992-Q3\UKDA-5888-stata8\stata8\qlfsjs92.dta"
gen year=1992
gen quarter=3
rename conmpy CONMPY
rename thiswv THISWV
//rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
//rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
rename healyl HEALYL
rename paidhra PAIDHRA
gen EMPTEN=1992-CONMPY
keep socmajm THISWV qual0 qual1 qual2 year quarter mpnor PUBLICR INECACR PAIDHRA HEALYL FTPTWK govtor AGE SEX subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic cured GRSSWK qual0 qual1 qual2
sa "Output\LFS_92_Q3.dta", replace

use  "1992-Q2\UKDA-5887-stata8\stata8\qlfsaj92.dta"
gen year=1992
gen quarter=2
rename conmpy CONMPY
rename thiswv THISWV
//rename piwt* PIWT*
rename age AGE
rename sex SEX
//rename ilodefr ILODEFR
//rename mardy* MARDY*
rename cameyr CAMEYR
//rename emplen EMPLEN
//rename ethcen15 ETHCEN15
//rename ethcen6 ETHCEN6
//rename ethmx ETHMX
//rename irend2 IREND2 
//rename levqual* LEVQUAL* 
//rename unembn1 UNEMBN1 
//rename benfts BENFTS 
//rename country COUNTRY 
//rename sincom SINCOM 
//rename sngdeg SNGDEG 
//rename stucur STUCUR 
rename grsswk GRSSWK 
//rename numal NUMAL 
//rename numol* NUMOL* 
//rename undemp UNDEMP
//rename healyl HEALYL
//rename paidhra PAIDHRA
gen EMPTEN=1992-CONMPY
keep socmajm THISWV qual0 qual1 qual2 year quarter mpnor PUBLICR INECACR PAIDHRA HEALYL FTPTWK govtor AGE SEX subjct1 marcon CAMEYR EMPTEN ethcen ethnica ethnic cured GRSSWK qual0 qual1 qual2
sa "Output\LFS_92_Q2.dta", replace
*/

******************************B.Combining Datasets******************************

*The append command is useful if you have two datasets each containing the same
*variables of interest, it will combine them into a single dataset

//append using "Output\LFS_93_Q1.dta"
append using "Output\LFS_93_Q2.dta"
append using "Output\LFS_93_Q3.dta"
append using "Output\LFS_93_Q4.dta"
append using "Output\LFS_94_Q1.dta"
append using "Output\LFS_94_Q2.dta"
append using "Output\LFS_94_Q3.dta"
append using "Output\LFS_94_Q4.dta"
append using "Output\LFS_95_Q1.dta"
append using "Output\LFS_95_Q2.dta"
append using "Output\LFS_95_Q3.dta"
append using "Output\LFS_95_Q4.dta"
append using "Output\LFS_96_Q1.dta"
append using "Output\LFS_96_Q2.dta"
append using "Output\LFS_96_Q3.dta"
append using "Output\LFS_96_Q4.dta"
append using "Output\LFS_97_Q1.dta"
append using "Output\LFS_97_Q2.dta"
append using "Output\LFS_97_Q3.dta"
append using "Output\LFS_97_Q4.dta"
append using "Output\LFS_98_Q1.dta"
append using "Output\LFS_98_Q2.dta"
append using "Output\LFS_98_Q3.dta"
append using "Output\LFS_98_Q4.dta"
append using "Output\LFS_99_Q1.dta"
append using "Output\LFS_99_Q2.dta"
append using "Output\LFS_99_Q3.dta"
append using "Output\LFS_99_Q4.dta"
append using "Output\LFS_00_Q1.dta"
append using "Output\LFS_00_Q2.dta"
append using "Output\LFS_00_Q3.dta"
append using "Output\LFS_00_Q4.dta"
//append using "Output\LFS_01_Q1.dta"
append using "Output\LFS_01_Q2.dta"
append using "Output\LFS_01_Q3.dta"
append using "Output\LFS_01_Q4.dta"
append using "Output\LFS_02_Q1.dta"
append using "Output\LFS_02_Q2.dta"
append using "Output\LFS_02_Q3.dta"
append using "Output\LFS_02_Q4.dta"
append using "Output\LFS_03_Q1.dta"
append using "Output\LFS_03_Q2.dta"
append using "Output\LFS_03_Q3.dta"
append using "Output\LFS_03_Q4.dta"
append using "Output\LFS_04_Q1.dta"
append using "Output\LFS_04_Q2.dta"
append using "Output\LFS_04_Q3.dta"
append using "Output\LFS_04_Q4.dta"
append using "Output\LFS_05_Q1.dta"
append using "Output\LFS_05_Q2.dta"
append using "Output\LFS_05_Q3.dta"
append using "Output\LFS_05_Q4.dta"
append using "Output\LFS_06_Q1.dta"
append using "Output\LFS_06_Q2.dta"
append using "Output\LFS_06_Q3.dta"
append using "Output\LFS_06_Q4.dta"
append using "Output\LFS_07_Q1.dta"
append using "Output\LFS_07_Q2.dta"
append using "Output\LFS_07_Q3.dta"
append using "Output\LFS_07_Q4.dta"
append using "Output\LFS_08_Q1.dta"
append using "Output\LFS_08_Q2.dta"
append using "Output\LFS_08_Q3.dta"
append using "Output\LFS_08_Q4.dta"
append using "Output\LFS_09_Q1.dta"
append using "Output\LFS_09_Q2.dta"
append using "Output\LFS_09_Q3.dta"
append using "Output\LFS_09_Q4.dta"
append using "Output\LFS_10_Q1.dta"
append using "Output\LFS_10_Q2.dta"
append using "Output\LFS_10_Q3.dta"
append using "Output\LFS_10_Q4.dta"
append using "Output\LFS_11_Q1.dta"
append using "Output\LFS_11_Q2.dta"
append using "Output\LFS_11_Q3.dta"
append using "Output\LFS_11_Q4.dta"
append using "Output\LFS_12_Q1.dta"
append using "Output\LFS_12_Q2.dta"
append using "Output\LFS_12_Q3.dta"
append using "Output\LFS_12_Q4.dta"
append using "Output\LFS_13_Q1.dta"
append using "Output\LFS_13_Q2.dta"
append using "Output\LFS_13_Q3.dta"
append using "Output\LFS_13_Q4.dta"
append using "Output\LFS_14_Q1.dta"
append using "Output\LFS_14_Q2.dta"
append using "Output\LFS_14_Q3.dta"
append using "Output\LFS_14_Q4.dta"
append using "Output\LFS_15_Q1.dta"
append using "Output\LFS_15_Q2.dta"
append using "Output\LFS_15_Q3.dta"
append using "Output\LFS_15_Q4.dta"
append using "Output\LFS_16_Q1.dta"
append using "Output\LFS_16_Q2.dta"
append using "Output\LFS_16_Q3.dta"
append using "Output\LFS_16_Q4.dta"
append using "Output\LFS_17_Q1.dta"
append using "Output\LFS_17_Q2.dta"
append using "Output\LFS_17_Q3.dta"
append using "Output\LFS_17_Q4.dta"
append using "Output\LFS_18_Q1.dta"
append using "Output\LFS_18_Q2.dta"
append using "Output\LFS_18_Q3.dta"
append using "Output\LFS_18_Q4.dta"
append using "Output\LFS_19_Q1.dta"
append using "Output\LFS_19_Q2.dta"
append using "Output\LFS_19_Q3.dta"
append using "Output\LFS_19_Q4.dta"
append using "Output\LFS_20_Q1.dta"
append using "Output\LFS_20_Q2.dta"
append using "Output\LFS_20_Q3.dta"
// this adds the data as rows i.e. appends to the bottom to create a 
// repeated cross-section, repeat for as many waves as required replace the 
// filepath with the location where you have saved the data
sa "Output\LFS_Combned.dta", replace